// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucmmxifvuxrnxjmmpczm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbW14aWZ2dXhybnhqbW1wY3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MzgxMTEsImV4cCI6MjA4OTQxNDExMX0.MRDjMiEHNwr1P_3vM4HwYs9613bkRTp2PMMBDh4NCSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});